### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by am11** [mcb2001/CSharp.Ulid#3]
This is a useful library and I (and likely more people) would like to consume it via NuGet.

If you could:

1. create NuGet publish key: https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-the-dotnet-cli#acquire-your-api-key
2. create GH secret with NuGet publish key: https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-an-organization
    * GitHub actions injects the secrets by name during the workflow run; `main.yml` file will only have:
`${{ secrets.NAME_YOU_CHOSE }}`

and tell me the name/alias of secret you chose, i can update the workflow with publish step, so when you will create and push a new git tag, e.g. `git tag v1.0.0 && git push --tags`, it will automagically publish v1.0.0 of this library to nuget.org, and also create a GitHub release for that tag.

**Comment by mcb2001** [comment]
Hi Am11
I made the key "NUGET_ULID_API_KEY".
The package needs to be named in the scope "*ulid*".

**Comment by am11** [comment]
@mcb2001, it looks like ulid is already taken https://www.nuget.org/packages/ulid/. `ulid.net` is available.

**Comment by mcb2001** [comment]
Sorry, it formatted it based on MarkDown.
You can name it what ever, as long as the letters u, l, i and d are next to each other :-)
@am11

**Comment by am11** [comment]
First version is published to nuget.org https://www.nuget.org/packages/ulid.net. 🙂
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/3840695/99517179-bea1b000-2997-11eb-9e9b-7ed91e8419dd.png">
